# Generated by Django 2.2.1 on 2019-11-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('distanciaRuta', models.IntegerField()),
                ('asientos', models.IntegerField()),
                ('ruta', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'autobuses',
            },
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='inventory_id',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
