# Generated by Django 2.2.1 on 2019-12-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'asientos',
            },
        ),
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('asientos', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'autobuses',
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.FloatField()),
                ('nombre_cleiente', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=30)),
                ('asiento', models.CharField(max_length=3)),
                ('total', models.FloatField()),
                ('autobus_id', models.ForeignKey(on_delete=models.SET(-1), to='example.Autobus')),
            ],
            options={
                'db_table': 'boletos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='ClaseAutobus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'clases_autobus',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'metodos_pagos',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField()),
                ('costo', models.FloatField()),
                ('hora_salida', models.CharField(max_length=20)),
                ('ciudad_destino_id', models.ForeignKey(on_delete=models.SET(-1), to='example.Ciudad')),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='inventory_id',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='boleto',
            name='clase_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.ClaseAutobus'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='metodopago_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.MetodoPago'),
        ),
        migrations.AddField(
            model_name='autobus',
            name='clase',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.ClaseAutobus'),
        ),
        migrations.AddField(
            model_name='autobus',
            name='ruta',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.Ruta'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='autobus_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.Autobus'),
        ),
    ]
